server:
  port: 9090

spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka




#server:
#  port: 9090
#
#spring:
#  application:
#    name: agent-service
#  ai:
#    ollama:
#      base-url: http://localhost:11434
#      chat:
#        options:
#          model: llama3.1
#
#eureka:
#  instance:
#    hostname: localhost
#    prefer-ip-address: false
#    instance-id: ${spring.application.name}:${server.port}
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka